language: node_js
node_js:
  - "7.0.0"
dist: trusty
services:
  - postgresql
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8
before_script:
  - sudo apt-get install -y g++ make python
  - npm install
  - psql -c 'create database liberac;' -U postgres
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &